from __future__ import annotations

from typing import Dict

# Default column descriptions for known dataset types.
# These can be overridden per upload when the frontend supplies custom descriptions.

DEFAULT_COLUMN_DESCRIPTIONS: Dict[str, Dict[str, str]] = {
    "sales": {
        "invoice_id": "Unique invoice number generated by the POS system",
        "invoice_date": "Invoice creation date and time",
        "item_id": "SKU or product identifier",
        "item_name": "Human-friendly product name",
        "quantity": "Quantity sold for this line item",
        "unit_price": "Gross unit price before discount (INR)",
        "discount": "Discount applied to this line item (INR)",
        "net_sales": "Total revenue for this line after discount (INR)",
        "staff_id": "Store associate who handled the sale",
        "channel": "Sales channel (e.g., walk-in, online)",
    },
    "inventory": {
        "item_id": "SKU or product identifier",
        "item_name": "Human-friendly product name",
        "category": "Product category/group",
        "stock_on_hand": "Current inventory units available",
        "quantity": "Current inventory units available",
        "qty": "Current inventory units available",
        "stock": "Current inventory units available",
        "stock_level": "Current inventory units available",
        "count": "Current inventory units available",
        "reorder_point": "Minimum stock threshold before reordering",
        "cost_price": "Cost price per unit (INR)",
        "selling_price": "Regular selling price per unit (INR)",
        "supplier": "Preferred supplier for the item",
        "last_restocked_at": "Timestamp of the last restock",
    },
    "staff": {
        "staff_id": "Unique identifier for the staff member",
        "staff_name": "Name of the staff member",
        "role": "Primary role/designation of the staff member",
        "store_branch": "Store or branch the staff member belongs to",
        "joined_at": "Date the staff member joined the company",
        "phone": "Contact number",
        "email": "Contact email",
        "status": "Employment status (active, on leave, resigned)",
    },
    "transactions": {
        "transaction_id": "Unique identifier for the payment transaction",
        "invoice_id": "Invoice associated with this payment",
        "payment_mode": "Payment mode (cash, card, UPI, etc.)",
        "amount": "Amount paid in this transaction (INR)",
        "paid_at": "Timestamp for when the payment was recorded",
        "reference": "External payment reference or UPI ID",
        "status": "Transaction status (success, failed, pending)",
    },
}


def merge_descriptions(dataset_type: str, overrides: Dict[str, str] | None) -> Dict[str, str]:
    """Merge default descriptions with user-provided overrides."""
    base = DEFAULT_COLUMN_DESCRIPTIONS.get(dataset_type, {}).copy()
    if overrides:
        for column, description in overrides.items():
            if description:
                base[column] = description
    return base
